[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
byteorder = "1.4"
hashbrown = "0.14"

[dev-dependencies]
tempfile = "3.6"